# Generated by Django 5.0.3 on 2024-04-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.BigIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('salary', models.BigIntegerField()),
                ('domain', models.CharField(max_length=50)),
            ],
        ),
    ]
