# Generated by Django 5.0.3 on 2024-04-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empdetails',
            name='mobile',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
